### ISSUE TITLE
Cannot read property 'decrypt'/'isPublic' of undefined

### ISSUE THREAD

**Issue by lidskialf** [fishat64/NNSKS#1]
Hello,

I got this errors on start & by uploading a key..

See: https://www.nopaste.eu/p?q=WXFRTFg

Kind regards,
Lidskialf

**Comment by fishat64** [comment]
Hey Lidskialf, 

I get the same errors when "privkey" and "pubkey" in your settings-default.json/gpg.json are not or wrong defined.
So I think somewhere there might be the problem? 

Best regards
fishat64

**Comment by lidskialf** [comment]
Hi fishat64,

Thats my gpg.json
See: https://www.nopaste.eu/p?q=OVgwamY
Maybe i miss understand the json config i must put a real privkey/publickey in the json config?
Maybe of the sending Email?

Kind regards,
Lidskialf

**Comment by fishat64** [comment]
Exactly, the private and public keys are for signing the outgoing mails and the public keys in the database. 

Yeah, the keypair of the sending email, you can define the sending email now in the json config, in an earlier version it was hardcoded.

Best regards
fishat64

**Comment by lidskialf** [comment]
Hi fishat64,

While preparing to run:
gpg.json: parse error reading settings file

I think my used syntax for adding the keys is wrong?
See: https://www.nopaste.eu/p?q=dGh0OHc

Kind regards,
Lidskialf

**Comment by fishat64** [comment]
Yeah, json does not support multi line strings, so you have to split them up in an array of lines of Strings.
Hope this helps!

Best regards,
fishat64

**Comment by lidskialf** [comment]
Hi fishat64,

Now its working thanks for your help! 

Kind regards,
Lidskialf
